sudo: false

language: python

python:
  - 3.6.5

before_install:
  - sudo apt-get update

install:
  - git clone https://github.com/github/gitignore.git
  - git clone https://github.com/alexkaratarakis/gitattributes.git

before_script:
  - git remote rm origin
  - git remote add origin https://username:${GIHUB_TOKEN}@github.com/Richienb/git-files.git

script:
  - python generate.py $PWD
  
after_success:
  - git add $PWD/files/.gitignore
  - git add $PWD/files/.gitattributes
  - git commit -m "Update Git Files"
  - git push origin master

notifications:
  email: false
