sudo: false

language: python

python:
  - 3.6.5

before_install:
  - git config --global user.email "richiebendall@gmail.com"
  - git config --global user.name "Richienb"

install:
  - git clone https://Richienb:${github_token}@github.com/Richienb/git-files.git
  - cd git-files
  - git clone https://github.com/github/gitignore.git
  - git clone https://github.com/alexkaratarakis/gitattributes.git

script:
  - python generate.py $PWD
  
after_success:
  - git add $PWD/files/.gitignore
  - git add $PWD/files/.gitattributes
  - git commit -m "Update Git Files [skip ci]"
  - git push

notifications:
  email: false
