sudo: false

language: python

python:
  - 3.6.5

before_install:
  - git remote set-url origin https://Richienb:${github_token}@github.com/Richienb/git-files.git
  - git config --global user.email "richiebendall@gmail.com"
  - git config --global user.name "Richienb"

install:
  - pip install -r requirements.txt
  - git clone https://github.com/github/gitignore.git
  - git clone https://github.com/alexkaratarakis/gitattributes.git

before_script:
  - autopep8 -v -i -r -a -a -a $PWD/src
  - git add generate.py
  - git commit -m "Normalised generation file to follow the PEP8 specification [skip ci]

script:
  - python generate.py $PWD
  - git add -f $PWD/files/.gitignore $PWD/files/.gitattributes
  - git commit -m "Update Git Files [skip ci]"

after_success:
  - pasteurize generate.py
  - git add generate.py
  - git commit -m "Added backwards compatibility [skip ci]"
  - git push

notifications:
  email: false
